image:
  repository: bolt
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  nodePort: null

persistence:
  storageClass: ""
  size: 1Gi

gateway:
  enabled: false
  name: gateway
  namespace: ""
  sectionName: http

hostnames: []
